<a href="https://colab.research.google.com/github/anuhingankar9922-hub/-Python-Basic-Projects/blob/main/Task14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. (Array Properties) Create a 2D array of shape (5, 6) filled with random integers between 10 and 100. Print the following: Shape of the array Total number of elements (size) Data type (dtype)

In [29]:
import numpy as np
arr=np.random.randint(10, 101, (5, 6))
print("Array: ")
print(arr)

print("\nShape of the array: ", arr.shape)
print("\nTotal number of elements: ", arr.size)
print("\nData type: ", arr.dtype)

Array: 
[[81 55 89 48 17 79]
 [35 53 23 36 87 68]
 [98 75 94 55 72 76]
 [44 43 64 68 33 63]
 [60 48 53 41 35 17]]

Shape of the array:  (5, 6)

Total number of elements:  30

Data type:  int64


Q2.( Statistical Methods - Basic) Generate a 1D array of 20 random numbers between 1 and 50 using np.random.randint(). Print: Minimum value and its index (argmin) Maximum value and its index (argmax) Sum of all elements Mean and Standard Deviation

In [30]:
import numpy as np
arr = np.random.randint(1, 51, 20)
print("Array:")
print(arr)

print("\nMinimum value:", np.min(arr))
print("Index of minimum value:", np.argmin(arr))

print("\nMaximum value:", np.max(arr))
print("Index of maximum value:", np.argmax(arr))

print("\nSum of elements:", np.sum(arr))

print("Mean:", np.mean(arr))

print("Standard Deviation:", np.std(arr))

Array:
[26 44 18 16 20 38  4 37 37  4  3 34 47 49  3 20 18 30  4  5]

Minimum value: 3
Index of minimum value: 10

Maximum value: 49
Index of maximum value: 13

Sum of elements: 457
Mean: 22.85
Standard Deviation: 15.512172639575672


Q3. (Statistical Methods on 2D Array) Create a 4 5 matrix of random integers between 20 and 80. For the entire matrix, print: Minimum and maximum value Sum of all elements Mean and Standard Deviation Then print the sum of each row and each column.

In [31]:
import numpy as np
arr = np.random.randint(20, 81, (4, 5))
print("4x5 Matrix:")
print(arr)

print("\nMinimum value:", np.min(arr))
print("Maximum value:", np.max(arr))
print("Sum of elements:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

print("\nSum of row:",np.sum(arr, axis=1))

print("\nSum of column:",np.sum(arr, axis=0))

4x5 Matrix:
[[46 65 68 35 26]
 [60 45 28 45 20]
 [31 45 67 26 47]
 [30 64 26 64 21]]

Minimum value: 20
Maximum value: 68
Sum of elements: 859
Mean: 42.95
Standard Deviation: 16.39352006129251

Sum of row: [240 198 216 205]

Sum of column: [167 219 189 170 114]


Q4.(Reshape) Create a 1D array containing numbers from 1 to 24 using np.arange().Reshape it into (4, 6) Reshape it into (3, 8) Reshape it into (2, 3, 4) (3D array) Print all reshaped arrays with their shapes.

In [32]:
import numpy as np
arr = np.arange(1, 25)
print("1D Array:")
print(arr)
print("Shape:", arr.shape)

arr1 = arr.reshape(4, 6)
print("\nReshaped 2D Array 4-6:")
print(arr1)
print("Shape:", arr1.shape)

arr2 = arr.reshape(3, 8)
print("\nReshaped 2D Array 3-8:")
print(arr2)
print("Shape:", arr2.shape)

arr3 = arr.reshape(2, 3, 4)
print("\nReshaped 3D Array 2-3-4:")
print(arr3)
print("Shape:", arr3.shape)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)

Reshaped 2D Array 4-6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshaped 2D Array 3-8:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshaped 3D Array 2-3-4:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


Q5. NumPy Indexing - 1D & 2D Create the following array: Python arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]) Perform the following indexing: Extract first row Extract last column Extract center 2x2 submatrix Extract all even numbers from the array using boolean indexing

In [33]:
import numpy as np
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]])

print("Array:")
print(arr)

print("\nFirst Row:")
print(arr[0])

print("\nLast Column:")
print(arr[:, -1])

print("\nCenter 2x2 Submatrix:")
print(arr[1:3, 1:3])

print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


Q6. (Advanced Indexing) Create a 5x5 matrix of random integers between 1 and 100. Print the diagonal elements Print elements greater than 50 Replace all elements less than 30 with 0 Print the modified array

In [34]:
import numpy as np
arr = np.random.randint(1, 101, (5, 5))

print("Matrix:")
print(arr)

print("\nDiagonal Elements:",np.diag(arr))

print("\nElements Greater Than 50:",arr[arr > 50])

arr[arr < 30] = 0
print("\nModified Matrix:")
print(arr)

Matrix:
[[81 94 70 82 93]
 [16 47 61 15 68]
 [65 20  2 26 58]
 [53 26 30 59 46]
 [64 53 96 31 63]]

Diagonal Elements: [81 47  2 59 63]

Elements Greater Than 50: [81 94 70 82 93 61 68 65 58 53 59 64 53 96 63]

Modified Matrix:
[[81 94 70 82 93]
 [ 0 47 61  0 68]
 [65  0  0  0 58]
 [53  0 30 59 46]
 [64 53 96 31 63]]


Q7.( Arithmetic Operations) Create two arrays: a = np.array([10, 20, 30, 40]) b = np.array([1, 2, 3, 4]) Perform and print: Addition, Subtraction, Multiplication, Division Element-wise power (**) Modulo operation %

In [35]:
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("1st Array:",a)
print("2nd Array:",b)

print("\nAddition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Power:",a**b)
print("Modulo:",a%b)

1st Array: [10 20 30 40]
2nd Array: [1 2 3 4]

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [     10     400   27000 2560000]
Modulo: [0 0 0 0]


Q8.( Matrix Multiplication) Create two 3x3 matrices: A = np.array ([[1,2,3],[4,5,6],[7,8,9]]) B = np.array ([[9,8,7],[6,5,4],[3,2,1]]) Perform: Element-wise multiplication (*) Matrix multiplication (@ or np.dot()) Print both results and explain the difference in comments.

In [36]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

element_mul=A*B

matrix_mult = A @ B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nElement-wise Multiplication:")
print(element_mul)

print("\nMatrix Multiplication:")
print(matrix_mult)

# Difference Between (*) and (@ or np.dot()):
# * multiplies corresponding elements of both matrices.
# @ or np.dot() performs matrix multiplication

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Q9. (Combined - Properties + Operations + Indexing) Generate a 6x6 matrix of random numbers using np.random.randn(). Print its shape, size, and dtype. Find the index of the maximum and minimum value. Extract the top-left 3x3 submatrix. Replace all negative numbers with their absolute value. Print the mean of the modified matrix.

In [37]:
import numpy as np
arr=np.random.randn(6, 6)
print("Matrix:")
print(arr)

print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

print("\nIndex of Maximum Value:", np.unravel_index(np.argmax(arr), arr.shape))
print("Index of Minimum Value:", np.unravel_index(np.argmin(arr), arr.shape))
print("\nTop-Left 3x3 Submatrix:")
print(arr[:3, :3])

arr[arr<0]=np.abs(arr[arr<0])

print("\nModified Matrix:")
print(arr)

print("\nMean of Modified Matrix:", np.mean(arr))

Matrix:
[[ 0.07482581  0.65878431 -0.3154237   1.19564727  0.91373713  1.24004584]
 [-0.84484135  0.16896439 -0.04530544 -0.87274548 -0.36463927  1.2683197 ]
 [ 0.08938933 -0.45577259 -1.04320056  0.19679552  1.59000364 -0.35844673]
 [-0.97435062  0.17315368 -0.91340183 -0.12714763 -0.30476909 -0.34993747]
 [-1.23302133  0.10412922 -0.15527761 -1.84019169 -2.80591171 -1.18910504]
 [ 0.07885364  0.22796285  0.23303114  0.37644766  1.61760702  0.53223374]]

Shape: (6, 6)
Size: 36
Data Type: float64

Index of Maximum Value: (np.int64(5), np.int64(4))
Index of Minimum Value: (np.int64(4), np.int64(4))

Top-Left 3x3 Submatrix:
[[ 0.07482581  0.65878431 -0.3154237 ]
 [-0.84484135  0.16896439 -0.04530544]
 [ 0.08938933 -0.45577259 -1.04320056]]

Modified Matrix:
[[0.07482581 0.65878431 0.3154237  1.19564727 0.91373713 1.24004584]
 [0.84484135 0.16896439 0.04530544 0.87274548 0.36463927 1.2683197 ]
 [0.08938933 0.45577259 1.04320056 0.19679552 1.59000364 0.35844673]
 [0.97435062 0.17315368 0.9

Q10. (Mini Project - Student Performance Analysis) Create a NumPy-based Student Marks Analyzer: Generate a 2D array of shape (10 students × 5 subjects) with random marks between 30 and 100. Print the array. For each student, calculate total marks and average. Find the student with highest and lowest total marks (use argmax/argmin). Calculate overall class mean and standard deviation. Reshape the array if needed and demonstrate indexing to extract marks of top 3 students. Add proper comments explaining each step.

In [38]:
import numpy as np                         #imports the NumPy library and uses np as its short name (alias).

marks=np.random.randint(30, 101, (10, 5))  #generates random integers from 30 to 100.
print("Student Marks (10 x 5):")
print(marks)

total=np.sum(marks, axis=1)                #np.sum() adds the numbers, and axis=1 calculates the sum across each row.
print("\nTotal Marks of Each Student:")
print(total)

average=np.mean(marks, axis=1)             #calculates the average marks of each student.
print("\nAverage Marks of Each Student:")
print(average)

high=np.argmax(total)                      #returns the index of the largest value.
print("\nStudent with Highest Total Marks:", high+1)
print("Highest Total Marks:", total[high])

low=np.argmin(total)                        #returns the index of the smallest value.
print("\nStudent with Lowest Total Marks:", low+1)
print("Lowest Total Marks:", total[low])

class_mean=np.mean(marks)                   #Overall class average
print("\nOverall Class Mean:", class_mean)

class_std=np.std(marks)                     #Standard deviation
print("Overall Class Standard Deviation:", class_std)

reshaped = marks.reshape(5, 10)             #Change array shape

print("\nReshaped Array (5x10):")
print(reshaped)

top3 = np.argsort(total)[-3:][::-1]         #Sort indices

print("\nTop 3 Students (by Total Marks):", top3+1)

print("\nMarks of Top 3 Students:")
print(marks[top3])

Student Marks (10 x 5):
[[ 87  57  62  47  46]
 [ 49 100  49  81  69]
 [ 91  99  91  36  46]
 [ 70  69  52  64  78]
 [ 88  95  63  57  44]
 [ 79  70  85  45 100]
 [ 81  68  37  71  67]
 [ 63  83  99  33  66]
 [ 65  98 100  84  66]
 [ 55  99  61  94  31]]

Total Marks of Each Student:
[299 348 363 333 347 379 324 344 413 340]

Average Marks of Each Student:
[59.8 69.6 72.6 66.6 69.4 75.8 64.8 68.8 82.6 68. ]

Student with Highest Total Marks: 9
Highest Total Marks: 413

Student with Lowest Total Marks: 1
Lowest Total Marks: 299

Overall Class Mean: 69.8
Overall Class Standard Deviation: 19.95795580714618

Reshaped Array (5x10):
[[ 87  57  62  47  46  49 100  49  81  69]
 [ 91  99  91  36  46  70  69  52  64  78]
 [ 88  95  63  57  44  79  70  85  45 100]
 [ 81  68  37  71  67  63  83  99  33  66]
 [ 65  98 100  84  66  55  99  61  94  31]]

Top 3 Students (by Total Marks): [9 6 3]

Marks of Top 3 Students:
[[ 65  98 100  84  66]
 [ 79  70  85  45 100]
 [ 91  99  91  36  46]]
