<a href="https://colab.research.google.com/github/anuhingankar9922-hub/-Python-Basic-Projects/blob/main/Task13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. (Basic Array Creation) Write a program to: a) Create a 1D array with elements [10, 20, 30, 40, 50] using np.array(). b) Create a 2D array (3X3) using np.array(). Print both arrays along with their shape and data type (dtype).

In [15]:
import numpy as np

arr=np.array([10, 20, 30, 40, 50])

arr2=np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

print("1D Array: ")
print(arr)
print("1D Array Shape: ",arr.shape)
print("1D Array Data Type: ",arr.dtype)

print("\n2D Array:")
print(arr2)
print("2D Array Shape: ",arr2.shape)
print("2D Array Data Type: ",arr2.dtype)

1D Array: 
[10 20 30 40 50]
1D Array Shape:  (5,)
1D Array Data Type:  int64

2D Array:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
2D Array Shape:  (3, 3)
2D Array Data Type:  int64


Q2. (np.zeros() and np.ones()) Create the following using NumPy: a) A 1D array of 8 zeros. b) A 2D array of shape (4, 4) filled with ones. c) A (3X3) matrix of zeros. Print all arrays with proper labels.

In [16]:
import numpy as np

arr=np.zeros(8)
print("1D Array of 8 Zeros: ")
print(arr)

arr2=np.ones([4,4])
print("\n2D Array of Ones: ")
print(arr2)

arr3=np.zeros((3,3))
print("\nMatrix of zeros: ")
print(arr3)

1D Array of 8 Zeros: 
[0. 0. 0. 0. 0. 0. 0. 0.]

2D Array of Ones: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Matrix of zeros: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q3. (np.arange()) Use np.arange() to create and print the following arrays: a) Numbers from 0 to 20 (step 1). b) Even numbers from 10 to 50. c) Numbers from 5 to 100 with step of 5.

In [25]:
import numpy as np

arr=np.arange(0,21,1)
print("Numbers from 0-20: ")
print(arr)

arr2=np.arange(10,51,2)
print("\nEven Numbers form 10-50: ")
print(arr2)

arr3=np.arange(5, 101, 5)
print("\nNumbers from 5-100 with step 5: ")
print(arr3)

Numbers from 0-20: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Even Numbers form 10-50: 
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

Numbers from 5-100 with step 5: 
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


Q4. (np.linspace()) Use np.linspace() to create: a) 10 equally spaced numbers between 0 and 5. b) 15 equally spaced numbers between -10 and 10. Print the arrays and their length.

In [26]:
import numpy as np

arr = np.linspace(0, 5, 10)
print("\n10 Equally Spaced Numbers between 0 and 5:")
print(arr)
print("\nLength:", len(arr))

arr2 = np.linspace(-10, 10, 15)
print("\n15 Equally Spaced Numbers between -10 and 10:")
print(arr2)
print("\nLength:", len(arr2))



10 Equally Spaced Numbers between 0 and 5:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Length: 10

15 Equally Spaced Numbers between -10 and 10:
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]

Length: 15


Q5.(Random Arrays) Write a program to generate: a) A 1D array of 10 random numbers between 0 and 1 using np.random.rand(). b) A (3X3) matrix of random numbers from standard normal distribution using np.random.randn().c) A 2D array (4X5) of random integers between 10 and 50 using np.random.randint(). Print all with proper headings.

In [27]:
import numpy as np
arr=np.random.rand(10)
print("Random number:")
print(arr)

arr2=np.random.randn(3,3)
print("\nMatrix of Random number ")
print(arr2)

arr3 = np.random.randint(10, 51, (4, 5))
print("\n2D array of Random Integers: ")
print(arr3)

Random number:
[0.44084073 0.91915951 0.9291181  0.14264505 0.10916477 0.58367549
 0.62898896 0.03942636 0.32814884 0.49567698]

Matrix of Random number 
[[ 0.19311116 -0.36583471  0.33699102]
 [ 0.19236046  0.90051631 -0.0747475 ]
 [-0.54827367  1.38743619 -0.68399927]]

2D array of Random Integers: 
[[38 12 20 22 27]
 [37 21 20 40 48]
 [35 17 22 28 18]
 [21 33 35 38 40]]


Q6. (Vectors and Basic Operations) Create two vectors: v1 = np.array([2, 4, 6, 8]) v2 = np.array([1, 3, 5, 7]) Perform and print: Addition Subtraction Element-wise multiplication Dot product

In [28]:
import numpy as np

v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

print("Vector 1: ",v1)
print("Vector 2: ",v2)

add=v1 + v2
print("\nAddition: ",add)

sub=v1 - v2
print("\nSubtraction: ",sub)

mul=v1 * v2
print("\nMultiplication: ",mul)

dot_pro=np.dot(v1, v2)
print("\nDot Product: ",dot_pro)

Vector 1:  [2 4 6 8]
Vector 2:  [1 3 5 7]

Addition:  [ 3  7 11 15]

Subtraction:  [1 1 1 1]

Multiplication:  [ 2 12 30 56]

Dot Product:  100


Q7. (Matrices and Operations) Create two 3X3 matrices: A = np.array([1,2,3,4,5,6,7,8,9]) B = np.array ([9,8,7,6,5,4,3,2,1]) Perform the following: Matrix addition Matrix multiplication (@ or np.dot()) Element-wise multiplication (*) Print the results clearly.

In [29]:
import numpy as np
A=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

B=np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]])

print("1st Matrix: ")
print(A)

print("\n2nd Matrix: ")
print(B)

add=A+B
print("\nAddition: ")
print(add)

matrix_mul=A@B
print("\nMatrix Multiplication: ")
print(matrix_mul)

element_mul=A*B
print("\nElement-wise Multiplication:")
print(element_mul)

1st Matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd Matrix: 
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition: 
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication: 
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Q8.( Properties of Arrays) Create a 4X4 matrix of random integers between 1 and 100. Print: Shape Dimension (ndim) Total number of elements (size) Data type Minimum and maximum values

In [33]:
import numpy as np

arr = np.random.randint(1, 101, (4, 4))
print("4x4 Random Integer Matrix:")
print(arr)

print("\nShape:", arr.shape)
print("Dimension:", arr.ndim)
print("Total Number of Elements:", arr.size)
print("Data Type:", arr.dtype)
print("Minimum Value:", arr.min())
print("Maximum Value:", arr.max())

4x4 Random Integer Matrix:
[[83 45 25 64]
 [48 66 41  6]
 [85 74 40 21]
 [ 9 67 12 41]]

Shape: (4, 4)

Dimension: 2

Total Number of Elements: 16

Data Type: int64

Minimum Value: 6

Maximum Value: 85


Q9. (Combined - Random + Reshape + Statistics) Generate a 1D array of 20 random integers between 1 and 50 using np.random.randint(). Reshape it into a (4X5) matrix. Print the sum, mean, and standard deviation of the matrix. Find the maximum value in each row.

In [1]:
import numpy as np

arr = np.random.randint(1, 51, 20)

matrix = arr.reshape(4, 5)
print("4x5 Matrix:")
print(matrix)

print("\nSum:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())

print("\nMaximum Value in Each Row:")
print(matrix.max(axis=1))

4x5 Matrix:
[[32 35 19 22  7]
 [26  6 19 34 26]
 [ 1 27 11 48 37]
 [23 11  1 48 31]]

Sum: 464
Mean: 23.2
Standard Deviation: 13.644046320648432

Maximum Value in Each Row:
[35 34 48 48]


Q10.( Mini Project - NumPy Application) Create a Simple Statistics Calculator using NumPy: Write a program that: Asks the user how many numbers they want to generate. Generates that many random numbers between 10 and 100 using np.random.randint(). Stores them in a 1D array. Prints: The array Mean, Median, Standard Deviation Minimum and Maximum Reshapes into a 2D array (if possible) and prints row-wise sum. Use proper comments and exception handling where needed.

In [17]:
import numpy as np
try:
    n = int(input("Enter how many numbers they want to generate: "))

    if n <= 0:
        print("Please enter a positive number.")
    else:
        arr = np.random.randint(10, 101, n)

        print("\nGenerated Array:")
        print(arr)

        print("\n\n<<< Statistics >>>")
        print("\nMean:", np.mean(arr))
        print("Median:", np.median(arr))
        print("Standard Deviation:", np.std(arr))
        print("Minimum Value:", np.min(arr))
        print("Maximum Value:", np.max(arr))

        rows = int(np.sqrt(n))

        while rows > 1:
            if n % rows == 0:
                cols = n // rows
                matrix = arr.reshape(rows, cols)

                print("\nReshaped 2D Array:")
                print(matrix)

                print("\nRow-wise Sum:")
                print(np.sum(matrix, axis=1))
                break

            rows -= 1
        else:
            print("\nCannot reshape into a proper 2D array.")

except Exception as e:
    print("Error:", e)

Enter how many numbers they want to generate: 18

Generated Array:
[27 93 54 68 15 21 74 55 47 83 52 57 73 85 76 87 96 58]


<<< Statistics >>>

Mean: 62.27777777777778
Median: 63.0
Standard Deviation: 23.335251243928873
Minimum Value: 15
Maximum Value: 96

Reshaped 2D Array:
[[27 93 54 68 15 21]
 [74 55 47 83 52 57]
 [73 85 76 87 96 58]]

Row-wise Sum:
[278 368 475]
